//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace WITS.to.XAF.WITSRej
{

    public partial class Commodity : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        bool fIsSystemObject;
        public bool IsSystemObject
        {
            get { return fIsSystemObject; }
            set { SetPropertyValue<bool>("IsSystemObject", ref fIsSystemObject, value); }
        }
        Guid fOrganization;
        [Indexed(Name = @"iOrganization_Commodity")]
        public Guid Organization
        {
            get { return fOrganization; }
            set { SetPropertyValue<Guid>("Organization", ref fOrganization, value); }
        }
        Guid fLocation;
        [Indexed(Name = @"iLocation_Commodity")]
        public Guid Location
        {
            get { return fLocation; }
            set { SetPropertyValue<Guid>("Location", ref fLocation, value); }
        }
        string fOrganizationName;
        public string OrganizationName
        {
            get { return fOrganizationName; }
            set { SetPropertyValue<string>("OrganizationName", ref fOrganizationName, value); }
        }
        string fLocationName;
        public string LocationName
        {
            get { return fLocationName; }
            set { SetPropertyValue<string>("LocationName", ref fLocationName, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>("IsActive", ref fIsActive, value); }
        }
        string fCreatedBy;
        public string CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<string>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        string fModifiedBy;
        public string ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<string>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fTag;
        [Size(SizeAttribute.Unlimited)]
        public string Tag
        {
            get { return fTag; }
            set { SetPropertyValue<string>("Tag", ref fTag, value); }
        }
        int fAccessStatus;
        public int AccessStatus
        {
            get { return fAccessStatus; }
            set { SetPropertyValue<int>("AccessStatus", ref fAccessStatus, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fOldKey;
        public string OldKey
        {
            get { return fOldKey; }
            set { SetPropertyValue<string>("OldKey", ref fOldKey, value); }
        }
        DateTime fCommodityINS;
        public DateTime CommodityINS
        {
            get { return fCommodityINS; }
            set { SetPropertyValue<DateTime>("CommodityINS", ref fCommodityINS, value); }
        }
        DateTime fCommodityEDT;
        public DateTime CommodityEDT
        {
            get { return fCommodityEDT; }
            set { SetPropertyValue<DateTime>("CommodityEDT", ref fCommodityEDT, value); }
        }
        short fFee;
        public short Fee
        {
            get { return fFee; }
            set { SetPropertyValue<short>("Fee", ref fFee, value); }
        }
        short fDefaultTab;
        public short DefaultTab
        {
            get { return fDefaultTab; }
            set { SetPropertyValue<short>("DefaultTab", ref fDefaultTab, value); }
        }
        string fGroup;
        public string Group
        {
            get { return fGroup; }
            set { SetPropertyValue<string>("Group", ref fGroup, value); }
        }
        string fShrink;
        public string Shrink
        {
            get { return fShrink; }
            set { SetPropertyValue<string>("Shrink", ref fShrink, value); }
        }
        short fMonth;
        public short Month
        {
            get { return fMonth; }
            set { SetPropertyValue<short>("Month", ref fMonth, value); }
        }
        byte fDay;
        public byte Day
        {
            get { return fDay; }
            set { SetPropertyValue<byte>("Day", ref fDay, value); }
        }
        decimal fStorage;
        public decimal Storage
        {
            get { return fStorage; }
            set { SetPropertyValue<decimal>("Storage", ref fStorage, value); }
        }
        string fUnits;
        public string Units
        {
            get { return fUnits; }
            set { SetPropertyValue<string>("Units", ref fUnits, value); }
        }
        decimal fConversion;
        public decimal Conversion
        {
            get { return fConversion; }
            set { SetPropertyValue<decimal>("Conversion", ref fConversion, value); }
        }
        string fCccId;
        public string CccId
        {
            get { return fCccId; }
            set { SetPropertyValue<string>("CccId", ref fCccId, value); }
        }
        string fReceiptKOG;
        public string ReceiptKOG
        {
            get { return fReceiptKOG; }
            set { SetPropertyValue<string>("ReceiptKOG", ref fReceiptKOG, value); }
        }
        bool fDeductDock;
        public bool DeductDock
        {
            get { return fDeductDock; }
            set { SetPropertyValue<bool>("DeductDock", ref fDeductDock, value); }
        }
        decimal fAllowableDock;
        public decimal AllowableDock
        {
            get { return fAllowableDock; }
            set { SetPropertyValue<decimal>("AllowableDock", ref fAllowableDock, value); }
        }
        decimal fSetDock;
        public decimal SetDock
        {
            get { return fSetDock; }
            set { SetPropertyValue<decimal>("SetDock", ref fSetDock, value); }
        }
        decimal fInCharge;
        public decimal InCharge
        {
            get { return fInCharge; }
            set { SetPropertyValue<decimal>("InCharge", ref fInCharge, value); }
        }
        decimal fOutCharge;
        public decimal OutCharge
        {
            get { return fOutCharge; }
            set { SetPropertyValue<decimal>("OutCharge", ref fOutCharge, value); }
        }
        decimal fSOPHead;
        public decimal SOPHead
        {
            get { return fSOPHead; }
            set { SetPropertyValue<decimal>("SOPHead", ref fSOPHead, value); }
        }
        decimal fSOPTotal;
        public decimal SOPTotal
        {
            get { return fSOPTotal; }
            set { SetPropertyValue<decimal>("SOPTotal", ref fSOPTotal, value); }
        }
        byte fTab;
        public byte Tab
        {
            get { return fTab; }
            set { SetPropertyValue<byte>("Tab", ref fTab, value); }
        }
        short fSort;
        public short Sort
        {
            get { return fSort; }
            set { SetPropertyValue<short>("Sort", ref fSort, value); }
        }
        [Association(@"CertificateReferencesCommodity")]
        public XPCollection<Certificate> Certificates { get { return GetCollection<Certificate>("Certificates"); } }
        [Association(@"LotNumberReferencesCommodity")]
        public XPCollection<LotNumber> LotNumbers { get { return GetCollection<LotNumber>("LotNumbers"); } }
    }

}
