//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace WITS.to.XAF.WITSRej
{

    public partial class SplitSetup : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        bool fIsSystemObject;
        public bool IsSystemObject
        {
            get { return fIsSystemObject; }
            set { SetPropertyValue<bool>("IsSystemObject", ref fIsSystemObject, value); }
        }
        Guid fOrganization;
        [Indexed(Name = @"iOrganization_SplitSetup")]
        public Guid Organization
        {
            get { return fOrganization; }
            set { SetPropertyValue<Guid>("Organization", ref fOrganization, value); }
        }
        Guid fLocation;
        [Indexed(Name = @"iLocation_SplitSetup")]
        public Guid Location
        {
            get { return fLocation; }
            set { SetPropertyValue<Guid>("Location", ref fLocation, value); }
        }
        string fOrganizationName;
        public string OrganizationName
        {
            get { return fOrganizationName; }
            set { SetPropertyValue<string>("OrganizationName", ref fOrganizationName, value); }
        }
        string fLocationName;
        public string LocationName
        {
            get { return fLocationName; }
            set { SetPropertyValue<string>("LocationName", ref fLocationName, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>("IsActive", ref fIsActive, value); }
        }
        string fCreatedBy;
        public string CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<string>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        string fModifiedBy;
        public string ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<string>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fTag;
        [Size(SizeAttribute.Unlimited)]
        public string Tag
        {
            get { return fTag; }
            set { SetPropertyValue<string>("Tag", ref fTag, value); }
        }
        int fAccessStatus;
        public int AccessStatus
        {
            get { return fAccessStatus; }
            set { SetPropertyValue<int>("AccessStatus", ref fAccessStatus, value); }
        }
        Customer fCustomer;
        [Association(@"SplitSetupReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>("Customer", ref fCustomer, value); }
        }
        int fSplitNumber;
        public int SplitNumber
        {
            get { return fSplitNumber; }
            set { SetPropertyValue<int>("SplitNumber", ref fSplitNumber, value); }
        }
        DateTime fSplitUsedData;
        public DateTime SplitUsedData
        {
            get { return fSplitUsedData; }
            set { SetPropertyValue<DateTime>("SplitUsedData", ref fSplitUsedData, value); }
        }
        string fSplitTagOld;
        [Size(7)]
        public string SplitTagOld
        {
            get { return fSplitTagOld; }
            set { SetPropertyValue<string>("SplitTagOld", ref fSplitTagOld, value); }
        }
        string fSplitIdOld;
        [Size(3)]
        public string SplitIdOld
        {
            get { return fSplitIdOld; }
            set { SetPropertyValue<string>("SplitIdOld", ref fSplitIdOld, value); }
        }
        [Association(@"LotNumberReferencesSplitSetup")]
        public XPCollection<LotNumber> LotNumbers { get { return GetCollection<LotNumber>("LotNumbers"); } }
        [Association(@"SplitDetailReferencesSplitSetup")]
        public XPCollection<SplitDetail> SplitDetails { get { return GetCollection<SplitDetail>("SplitDetails"); } }
    }

}
