//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace WITS.to.XAF.WITSRej
{

    public partial class SplitDetail : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        bool fIsSystemObject;
        public bool IsSystemObject
        {
            get { return fIsSystemObject; }
            set { SetPropertyValue<bool>("IsSystemObject", ref fIsSystemObject, value); }
        }
        Guid fOrganization;
        [Indexed(Name = @"iOrganization_SplitDetail")]
        public Guid Organization
        {
            get { return fOrganization; }
            set { SetPropertyValue<Guid>("Organization", ref fOrganization, value); }
        }
        Guid fLocation;
        [Indexed(Name = @"iLocation_SplitDetail")]
        public Guid Location
        {
            get { return fLocation; }
            set { SetPropertyValue<Guid>("Location", ref fLocation, value); }
        }
        string fOrganizationName;
        public string OrganizationName
        {
            get { return fOrganizationName; }
            set { SetPropertyValue<string>("OrganizationName", ref fOrganizationName, value); }
        }
        string fLocationName;
        public string LocationName
        {
            get { return fLocationName; }
            set { SetPropertyValue<string>("LocationName", ref fLocationName, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>("IsActive", ref fIsActive, value); }
        }
        string fCreatedBy;
        public string CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<string>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        string fModifiedBy;
        public string ModifiedBy
        {
            get { return fModifiedBy; }
            set { SetPropertyValue<string>("ModifiedBy", ref fModifiedBy, value); }
        }
        DateTime fModifiedOn;
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fTag;
        [Size(SizeAttribute.Unlimited)]
        public string Tag
        {
            get { return fTag; }
            set { SetPropertyValue<string>("Tag", ref fTag, value); }
        }
        int fAccessStatus;
        public int AccessStatus
        {
            get { return fAccessStatus; }
            set { SetPropertyValue<int>("AccessStatus", ref fAccessStatus, value); }
        }
        SplitSetup fSplitSetup;
        [Association(@"SplitDetailReferencesSplitSetup")]
        public SplitSetup SplitSetup
        {
            get { return fSplitSetup; }
            set { SetPropertyValue<SplitSetup>("SplitSetup", ref fSplitSetup, value); }
        }
        Customer fCustomer;
        [Association(@"SplitDetailReferencesCustomer1")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>("Customer", ref fCustomer, value); }
        }
        Customer fAffiliatedCustomer;
        [Association(@"SplitDetailReferencesCustomer")]
        public Customer AffiliatedCustomer
        {
            get { return fAffiliatedCustomer; }
            set { SetPropertyValue<Customer>("AffiliatedCustomer", ref fAffiliatedCustomer, value); }
        }
        double fDetCrop;
        public double DetCrop
        {
            get { return fDetCrop; }
            set { SetPropertyValue<double>("DetCrop", ref fDetCrop, value); }
        }
        double fDetDrying;
        public double DetDrying
        {
            get { return fDetDrying; }
            set { SetPropertyValue<double>("DetDrying", ref fDetDrying, value); }
        }
        double fDetStorage;
        public double DetStorage
        {
            get { return fDetStorage; }
            set { SetPropertyValue<double>("DetStorage", ref fDetStorage, value); }
        }
        string fDetTagOld;
        [Size(7)]
        public string DetTagOld
        {
            get { return fDetTagOld; }
            set { SetPropertyValue<string>("DetTagOld", ref fDetTagOld, value); }
        }
        string fDetAffilOld;
        [Size(3)]
        public string DetAffilOld
        {
            get { return fDetAffilOld; }
            set { SetPropertyValue<string>("DetAffilOld", ref fDetAffilOld, value); }
        }
        string fDetIdOld;
        [Size(3)]
        public string DetIdOld
        {
            get { return fDetIdOld; }
            set { SetPropertyValue<string>("DetIdOld", ref fDetIdOld, value); }
        }
    }

}
